### ISSUE TITLE
calculating wrong perplexity when using function find_optimal_sigmas

### ISSUE THREAD

**Issue by byte-drift** [nlml/tsne_raw#1]
In the function find_optimal_sigmas,you put one single row of X into function perplexity, which will invoke the function softmax.
  In softmax,you reset all diagonal elements.It will work in the situation of the whole X. However,as i've mentioned, you  put one single row of X into  it. And diagonal element will always be the first one! But which element shoule be reset depends on the row number,so it is wrong to reset the first element all the time.
  I'm working on tsne and i found your blog. It really helps me . Thanks a lot ! And I found the result of sigmas from my code is different from yours. then i found this "mistake"(i think it's a mistake but i'm not quite sure,so please check it if it's convenient). In high dimension this "mistake" won't matter a lot but i'm not comfortable about this-_-!

**Comment by nlml** [comment]
Ah, very well spotted!

I have (hopefully) fixed this with 53c2857606df0327367105ddbff22988bfd050a5

Glad I could help you out!
